import { Inter } from "next/font/google";
import "./globals.css";
import Navbars from "./component/Shared/Navbars";
import Footers from "./component/Shared/Footers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbars/>
        {children}
        <Footers/>
        </body>
    </html>
  );
}
